name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main # O cambia a master si tu rama principal se llama así

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-node-version: 18
          cache: 'npm'
          # Apuntamos el caché a la subcarpeta del frontend para máxima velocidad
          cache-dependency-path: helpdesk/frontend/package-lock.json

      - name: Install Dependencies
        # El comando 'working-directory' le ordena al robot viajar a tu carpeta frontend real
        working-directory: helpdesk/frontend
        run: npm install

      - name: Build Production HTML Assets
        working-directory: helpdesk/frontend
        run: npm run build

      - name: Deploy static bundle to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: helpdesk/frontend/dist # Ubicación física de la carpeta compilada por Webpack
          branch: gh-pages # Rama automática donde GitHub Actions colgará la web pública
